source "https://rubygems.org"

rails_version = ENV["RAILS_VERSION"] || "5.2.4.3"
puts "<---- Installing Rails at version '#{rails_version}'"
gem "rails", rails_version

gem "good_migrations", path: ".."
if /^[6789]/.match?(rails_version)
  gem "zeitwerk", git: "https://github.com/fxn/zeitwerk", branch: "main" # "~> 2.5"
end

gem "sqlite3"
