source "https://rubygems.org"

rails_version = ENV["RAILS_VERSION"] || "5.2.4.3"
puts "<---- Installing Rails at version '#{rails_version}'"
gem "rails", rails_version

gem "good_migrations", path: ".."

gem "sqlite3"
