source "https://rubygems.org"

if ENV["RAILS_VERSION"] == "edge"
  gem "rails", github: "rails/rails", branch: "main"
else
  rails_version = Gem::Version.new ENV.fetch("RAILS_VERSION", "7.2")
  gem "rails", rails_version.approximate_recommendation # ~> major.minor
end

gem "good_migrations", path: ".."

if ENV["RAILS_VERSION"] == "edge" || rails_version >= Gem::Version.new("8.0")
  gem "sqlite3", ">= 2.1"
else
  gem "sqlite3", "~> 1.7.3"
end

gem "zeitwerk", "~> 2.6"

gem "bootsnap", require: false

# activesupport 6.1 needs these but older rails got it from stdlib
if rails_version && Gem::Requirement.new("~> 6.1") === rails_version
  gem "bigdecimal" # since ruby 3.4
  gem "mutex_m" # since ruby 3.4
  gem "benchmark" # since ruby 4.0
end
