#!/usr/bin/env bash

set -euo pipefail

echo "---> Installing dependencies in example app"
cd example
bundle
bundle exec rake db:prepare
cd ..

echo "---> Running tests"
bundle exec rake

echo "---> Job's done!"
